[package]
name = "sk6812_rpi"
version = "1.0.0"
edition = "2021"
description = "SK6812RGBW library for RaspberryPi"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.13"
palette = "0.6"
bitvec = "1"